SELECT USER
FROM DUAL;
--==>> HR

--○ 세 개 이상의 테이블 조인 (JOIN)

-- 형식1 (SQL 1992 CODE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1, 테이블명2, 테이블명3
WHERE 테이블명1.컬럼명1 = 테이블명2.컬럼명1
  AND 테이블명2.컬럼명2 = 테이블명3.컬럼명2;

-- 형식2 (SQL 1999 CODE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1 JOIN 테이블명2
ON 테이블명1.컬럼명1 = 테이블명2.컬럼명1
        JOIN 테이블명3
        ON 테이블명2.컬럼명2 = 테이블명3.컬럼명2;

--○ HR 계정 소유의 테이블 또는 뷰 목록 조회
SELECT *
FROM TAB;
--==>>
/*
COUNTRIES	        TABLE	 (null)
DEPARTMENTS	        TABLE	 (null)
EMPLOYEES	        TABLE	 (null)
EMP_DETAILS_VIEW	VIEW	 (null)
JOBS	            TABLE	 (null)
JOB_HISTORY	        TABLE	 (null)
LOCATIONS	        TABLE	 (null)
REGIONS	            TABLE	 (null)
*/

--○ HR.JOBS, HR.EMPOYEES, HR.DEPARTMENTS 테이블을 대상으로
--  직원들의 FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME
--  항목을 조회한다
SELECT *
FROM JOBS;

SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

-- 1999 코드 기반
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
FROM JOBS J RIGHT JOIN EMPLOYEES E 
ON J.JOB_ID = E.JOB_ID
    LEFT JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 1992 코드 기반
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
    AND E.JOB_ID = J.JOB_ID;


--○ EMPLOYEES, DEPARTMENTS, JOBS, LOCATIONS, COUNTRIES, REGIONS 테이블을 대상으로
--   직원들의 데이터를 다음과 같이 조회한다.
--   FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME
--   , CITY, COUNTRY_NAME, REGION_NAME

-- 1999 코드
SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

SELECT *
FROM JOBS;

SELECT *
FROM LOCATIONS;

SELECT *
FROM COUNTRIES;

SELECT *
FROM REGIONS;

SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
    , L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON  E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID
    LEFT JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
    LEFT JOIN COUNTRIES C 
    ON C.COUNTRY_ID = L.COUNTRY_ID
    LEFT JOIN REGIONS R
    ON R.REGION_ID = C.REGION_ID;
    
-- 1992 코드
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
    , L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM EMPLOYEES E, DEPARTMENTS D , JOBS J, LOCATIONS L, COUNTRIES C , REGIONS R
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)`
    AND J.JOB_ID = E.JOB_ID
    AND L.LOCATION_ID(+) = D.LOCATION_ID
    AND C.COUNTRY_ID(+) = L.COUNTRY_ID
    AND R.REGION_ID(+) = C.REGION_ID;
    

